In [369]:
import pandas as pd
from glob import glob
import re

In [370]:
import os

print(os.getcwd())

/home/amrkhaled/work/Fitness_Tracker

In [371]:
single_file_acc = pd.read_csv("/home/amrkhaled/work/Fitness_Tracker/data/raw/MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

In [372]:
single_file_acc

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g)
0,1547472169751,2019-01-14T14:22:49.751,0.00,-0.147,0.702,-0.276
1,1547472169831,2019-01-14T14:22:49.831,0.08,-0.120,0.710,-0.360
2,1547472169911,2019-01-14T14:22:49.911,0.16,-0.160,0.768,-0.392
3,1547472169991,2019-01-14T14:22:49.991,0.24,-0.208,0.817,-0.379
4,1547472170071,2019-01-14T14:22:50.071,0.32,-0.223,0.839,-0.403
...,...,...,...,...,...,...
147,1547472181511,2019-01-14T14:23:01.511,11.76,-0.068,0.933,-0.345
148,1547472181591,2019-01-14T14:23:01.591,11.84,-0.075,0.903,-0.349
149,1547472181671,2019-01-14T14:23:01.671,11.92,-0.070,0.899,-0.361
150,1547472181751,2019-01-14T14:23:01.751,12.00,-0.067,0.941,-0.365
151,1547472181831,2019-01-14T14:23:01.831,12.08,-0.083,0.938,-0.366

In [373]:
single_file_gyro = pd.read_csv('./data/raw/MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv')

In [374]:
files = glob("./data/raw/MetaMotion/*.csv")
len(files)

187

In [375]:
data_path = "./data/raw/MetaMotion/"
f = files[0]

In [376]:
participant = f.split('-')[0].replace(data_path, '')

In [377]:
label = f.split('-')[1]

In [378]:
category = f.split('-')[2].rstrip("123").rstrip("_MetaWear_2019")

In [379]:
category

'heavy'

In [380]:

category = re.sub(r"\d+","",category.split("_")[0])

In [381]:
df = pd.read_csv(f)

In [382]:
df['participant'] = participant
df['label'] = label
df['category'] = category

In [383]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547472421400,2019-01-14T14:27:01.400,0.00,-0.181,0.796,-0.383,A,bench,heavy
1,1547472421480,2019-01-14T14:27:01.480,0.08,-0.192,0.823,-0.424,A,bench,heavy
2,1547472421560,2019-01-14T14:27:01.560,0.16,-0.203,0.808,-0.421,A,bench,heavy
3,1547472421640,2019-01-14T14:27:01.640,0.24,-0.217,0.833,-0.439,A,bench,heavy
4,1547472421720,2019-01-14T14:27:01.720,0.32,-0.206,0.845,-0.446,A,bench,heavy
...,...,...,...,...,...,...,...,...,...
151,1547472433480,2019-01-14T14:27:13.480,12.08,-0.094,0.924,-0.357,A,bench,heavy
152,1547472433560,2019-01-14T14:27:13.560,12.16,-0.104,0.901,-0.369,A,bench,heavy
153,1547472433640,2019-01-14T14:27:13.640,12.24,-0.087,0.881,-0.374,A,bench,heavy
154,1547472433720,2019-01-14T14:27:13.720,12.32,-0.094,0.893,-0.373,A,bench,heavy
155,1547472433800,2019-01-14T14:27:13.800,12.40,-0.100,0.907,-0.375,A,bench,heavy

In [384]:
acc_df = pd.DataFrame()
gyro_df = pd.DataFrame()

In [385]:
acc_set = 1
gyro_set = 1

In [386]:
for f in files:
    participant = f.split('-')[0].replace(data_path, '')
    label = f.split('-')[1]
    category = f.split('-')[2].rsplit("3")[0]
    category = re.sub(r"\d+","",category.split("_")[0])

    df = pd.read_csv(f)
    
    df['participant'] = participant
    df['label'] = label
    df['category'] = category

    if "Accelerometer" in f:
        df['set']=acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df], ignore_index=True)
    elif "Gyroscope" in f:
        df['set']=gyro_set
        gyro_set += 1
        gyro_df = pd.concat([gyro_df, df], ignore_index=True)

In [387]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547472421400,2019-01-14T14:27:01.400,0.00,-0.181,0.796,-0.383,A,bench,heavy,1
1,1547472421480,2019-01-14T14:27:01.480,0.08,-0.192,0.823,-0.424,A,bench,heavy,1
2,1547472421560,2019-01-14T14:27:01.560,0.16,-0.203,0.808,-0.421,A,bench,heavy,1
3,1547472421640,2019-01-14T14:27:01.640,0.24,-0.217,0.833,-0.439,A,bench,heavy,1
4,1547472421720,2019-01-14T14:27:01.720,0.32,-0.206,0.845,-0.446,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
23573,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,E,squat,heavy,94
23574,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,E,squat,heavy,94
23575,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,E,squat,heavy,94
23576,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,E,squat,heavy,94
23577,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,E,squat,heavy,94

In [388]:
gyro_df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
0,1547472420993,2019-01-14T14:27:00.993,0.00,2.317,-2.500,-9.695,A,bench,heavy,1
1,1547472421033,2019-01-14T14:27:01.033,0.04,3.110,-0.793,-9.207,A,bench,heavy,1
2,1547472421073,2019-01-14T14:27:01.073,0.08,3.232,2.134,-2.500,A,bench,heavy,1
3,1547472421113,2019-01-14T14:27:01.113,0.12,2.988,2.195,-11.159,A,bench,heavy,1
4,1547472421153,2019-01-14T14:27:01.153,0.16,18.354,-7.866,-14.451,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
47213,1547666063314,2019-01-16 20:14:23.314,19.48,-1.707,-0.671,1.585,E,squat,heavy,93
47214,1547666063354,2019-01-16 20:14:23.354,19.52,0.915,0.305,2.988,E,squat,heavy,93
47215,1547666063394,2019-01-16 20:14:23.394,19.56,5.854,-2.561,1.463,E,squat,heavy,93
47216,1547666063434,2019-01-16 20:14:23.434,19.60,4.268,0.549,-0.305,E,squat,heavy,93
47217,1547666063474,2019-01-16 20:14:23.474,19.64,-1.098,1.768,-0.122,E,squat,heavy,93

In [389]:
acc_df.index=pd.to_datetime(acc_df['epoch (ms)'], unit='ms')
gyro_df.index=pd.to_datetime(gyro_df['epoch (ms)'], unit='ms')

In [390]:
acc_df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-14 13:27:01.400,1547472421400,2019-01-14T14:27:01.400,0.00,-0.181,0.796,-0.383,A,bench,heavy,1
2019-01-14 13:27:01.480,1547472421480,2019-01-14T14:27:01.480,0.08,-0.192,0.823,-0.424,A,bench,heavy,1
2019-01-14 13:27:01.560,1547472421560,2019-01-14T14:27:01.560,0.16,-0.203,0.808,-0.421,A,bench,heavy,1
2019-01-14 13:27:01.640,1547472421640,2019-01-14T14:27:01.640,0.24,-0.217,0.833,-0.439,A,bench,heavy,1
2019-01-14 13:27:01.720,1547472421720,2019-01-14T14:27:01.720,0.32,-0.206,0.845,-0.446,A,bench,heavy,1
...,...,...,...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,1547666063089,2019-01-16 20:14:23.089,18.96,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,1547666063169,2019-01-16 20:14:23.169,19.04,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,1547666063249,2019-01-16 20:14:23.249,19.12,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,1547666063329,2019-01-16 20:14:23.329,19.20,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,1547666063409,2019-01-16 20:14:23.409,19.28,0.015,0.588,0.826,E,squat,heavy,94

In [391]:
acc_df.drop(columns=['epoch (ms)','time (01:00)','elapsed (s)'], inplace=True)
gyro_df.drop(columns=['epoch (ms)','time (01:00)','elapsed (s)'], inplace=True)

In [392]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-14 13:27:01.400,-0.181,0.796,-0.383,A,bench,heavy,1
2019-01-14 13:27:01.480,-0.192,0.823,-0.424,A,bench,heavy,1
2019-01-14 13:27:01.560,-0.203,0.808,-0.421,A,bench,heavy,1
2019-01-14 13:27:01.640,-0.217,0.833,-0.439,A,bench,heavy,1
2019-01-14 13:27:01.720,-0.206,0.845,-0.446,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94

In [393]:
acc_df .info()

<class 'pandas.DataFrame'>
DatetimeIndex: 23578 entries, 2019-01-14 13:27:01.400000 to 2019-01-16 19:14:23.409000
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   x-axis (g)   23578 non-null  float64
 1   y-axis (g)   23578 non-null  float64
 2   z-axis (g)   23578 non-null  float64
 3   participant  23578 non-null  str
 4   label        23578 non-null  str
 5   category     23578 non-null  str
 6   set          23578 non-null  int64
dtypes: float64(3), int64(1), str(3)
memory usage: 1.4 MB

In [395]:
files = glob("./data/raw/MetaMotion/*.csv")
def read_date_from_file(file):
    acc_df = pd.DataFrame()
    gyro_df = pd.DataFrame()

    acc_set = 1
    gyro_set = 1

    for f in files:
        participant = f.split('-')[0].replace(data_path, '')
        label = f.split('-')[1]
        category = f.split('-')[2].rsplit("3")[0]
        category = re.sub(r"\d+","",category.split("_")[0])

        df = pd.read_csv(f)
        
        df['participant'] = participant
        df['label'] = label
        df['category'] = category

        if "Accelerometer" in f:
            df['set']=acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df], ignore_index=True)
        elif "Gyroscope" in f:
            df['set']=gyro_set
            gyro_set += 1
            gyro_df = pd.concat([gyro_df, df], ignore_index=True)

    acc_df.index=pd.to_datetime(acc_df['epoch (ms)'], unit='ms')
    gyro_df.index=pd.to_datetime(gyro_df['epoch (ms)'], unit='ms')

    acc_df.drop(columns=['epoch (ms)','time (01:00)','elapsed (s)'], inplace=True)
    gyro_df.drop(columns=['epoch (ms)','time (01:00)','elapsed (s)'], inplace=True)

    return acc_df, gyro_df

acc_df, gyro_df = read_date_from_file(files)

In [396]:
read_date_from_file(files)

(                         x-axis (g)  y-axis (g)  z-axis (g) participant  \
 epoch (ms)
 2019-01-14 13:27:01.400      -0.181       0.796      -0.383           A
 2019-01-14 13:27:01.480      -0.192       0.823      -0.424           A
 2019-01-14 13:27:01.560      -0.203       0.808      -0.421           A
 2019-01-14 13:27:01.640      -0.217       0.833      -0.439           A
 2019-01-14 13:27:01.720      -0.206       0.845      -0.446           A
 ...                             ...         ...         ...         ...
 2019-01-16 19:14:23.089       0.012       0.596       0.815           E
 2019-01-16 19:14:23.169       0.009       0.528       0.821           E
 2019-01-16 19:14:23.249       0.015       0.554       0.746           E
 2019-01-16 19:14:23.329       0.006       0.574       0.824           E
 2019-01-16 19:14:23.409       0.015       0.588       0.826           E

                          label category  set
 epoch (ms)
 2019-01-14 13:27:01.400  bench    heavy    1
 2019-01-14 13:27:01.480  bench    heavy    1
 2019-01-14 13:27:01.560  bench    heavy    1
 2019-01-14 13:27:01.640  bench    heavy    1
 2019-01-14 13:27:01.720  bench    heavy    1
 ...                        ...      ...  ...
 2019-01-16 19:14:23.089  squat    heavy   94
 2019-01-16 19:14:23.169  squat    heavy   94
 2019-01-16 19:14:23.249  squat    heavy   94
 2019-01-16 19:14:23.329  squat    heavy   94
 2019-01-16 19:14:23.409  squat    heavy   94

 [23578 rows x 7 columns],
                          x-axis (deg/s)  y-axis (deg/s)  z-axis (deg/s)  \
 epoch (ms)
 2019-01-14 13:27:00.993           2.317          -2.500          -9.695
 2019-01-14 13:27:01.033           3.110          -0.793          -9.207
 2019-01-14 13:27:01.073           3.232           2.134          -2.500
 2019-01-14 13:27:01.113           2.988           2.195         -11.159
 2019-01-14 13:27:01.153          18.354          -7.866         -14.451
 ...                                 ...             ...             ...
 2019-01-16 19:14:23.314          -1.707          -0.671           1.585
 2019-01-16 19:14:23.354           0.915           0.305           2.988
 2019-01-16 19:14:23.394           5.854          -2.561           1.463
 2019-01-16 19:14:23.434           4.268           0.549          -0.305
 2019-01-16 19:14:23.474          -1.098           1.768          -0.122

                         participant  label category  set
 epoch (ms)
 2019-01-14 13:27:00.993           A  bench    heavy    1
 2019-01-14 13:27:01.033           A  bench    heavy    1
 2019-01-14 13:27:01.073           A  bench    heavy    1
 2019-01-14 13:27:01.113           A  bench    heavy    1
 2019-01-14 13:27:01.153           A  bench    heavy    1
 ...                             ...    ...      ...  ...
 2019-01-16 19:14:23.314           E  squat    heavy   93
 2019-01-16 19:14:23.354           E  squat    heavy   93
 2019-01-16 19:14:23.394           E  squat    heavy   93
 2019-01-16 19:14:23.434           E  squat    heavy   93
 2019-01-16 19:14:23.474           E  squat    heavy   93

 [47218 rows x 7 columns])

In [397]:
acc_df

,x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
epoch (ms),,,,,,,
2019-01-14 13:27:01.400,-0.181,0.796,-0.383,A,bench,heavy,1
2019-01-14 13:27:01.480,-0.192,0.823,-0.424,A,bench,heavy,1
2019-01-14 13:27:01.560,-0.203,0.808,-0.421,A,bench,heavy,1
2019-01-14 13:27:01.640,-0.217,0.833,-0.439,A,bench,heavy,1
2019-01-14 13:27:01.720,-0.206,0.845,-0.446,A,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-16 19:14:23.089,0.012,0.596,0.815,E,squat,heavy,94
2019-01-16 19:14:23.169,0.009,0.528,0.821,E,squat,heavy,94
2019-01-16 19:14:23.249,0.015,0.554,0.746,E,squat,heavy,94
2019-01-16 19:14:23.329,0.006,0.574,0.824,E,squat,heavy,94
2019-01-16 19:14:23.409,0.015,0.588,0.826,E,squat,heavy,94